version: 2
updates:
  - package-ecosystem: gomod
    directory: /backend
    schedule:
      interval: weekly
    groups:
      go:
        patterns: ["*"]
    commit-message:
      prefix: "build(deps)"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci(deps)"
