package install

import (
	"io"
	"io/fs"
	"os"
	"strings"
)

// launcherMarker identifies the launchers generated by OmaStore.
const launcherMarker = "# omastore-launcher"

// shellQuote wraps s in single quotes for sh.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// launcherScript generates the ~/.local/bin launcher. We use a script instead
// of a symlink because many apps locate their files from $0 / argv[0]
// (e.g. "$(dirname "$0")/../lib"), which breaks when $0 is the link.
func launcherScript(repo, target string) string {
	return "#!/bin/sh\n" + launcherMarker + " " + repo + "\n" +
		"exec " + shellQuote(target) + ` "$@"` + "\n"
}

// launcherTarget reads one of our launchers and returns the target executable;
// ok is false if p is not an OmaStore launcher.
func launcherTarget(p string) (target string, ok bool) {
	st, err := os.Lstat(p)
	if err != nil || !st.Mode().IsRegular() || st.Size() > 64<<10 {
		return "", false
	}
	f, err := os.Open(p)
	if err != nil {
		return "", false
	}
	defer f.Close()
	b, _ := io.ReadAll(io.LimitReader(f, 64<<10))
	lines := strings.Split(string(b), "\n")
	if len(lines) < 3 || lines[0] != "#!/bin/sh" || !strings.HasPrefix(lines[1], launcherMarker+" ") {
		return "", false
	}
	rest, found := strings.CutPrefix(lines[2], "exec '")
	if !found {
		return "", false
	}
	rest, found = strings.CutSuffix(rest, `' "$@"`)
	if !found {
		return "", false
	}
	return strings.ReplaceAll(rest, `'\''`, "'"), true
}

// isOurLink reports whether p is a launcher (or symlink, from older versions)
// pointing inside ownDir.
func isOurLink(p, ownDir string) bool {
	st, err := os.Lstat(p)
	if err != nil {
		return false
	}
	if st.Mode()&fs.ModeSymlink != 0 {
		t, err := os.Readlink(p)
		return err == nil && within(ownDir, t)
	}
	t, ok := launcherTarget(p)
	return ok && (ownDir == "" || within(ownDir, t))
}
